package assignment7;

/**
 * Created by Anthony on 11/28/2016.
 */
public enum ClientAction {
    REGISTER,LOGIN,UPDATEPASSWORD,
    SENDMESSAGE,SENDGROUPMESSAGE,MAKECHAT,
    GETMESSAGEHISTORY, GETGROUPMESSAGEHISTORY,
    GETFRIENDS,GETOFFLINEFRIENDS,GETSTRANGERS,
    ADDFRIEND,REMOVEFRIEND
}
