package assignment7;

/**
 * Created by Anthony on 11/28/2016.
 */
public enum ClientAction { REGISTER,LOGIN,SENDMESSAGE,UPDATEPASSWORD,MAKECHAT,GETFRIENDS,GETOFFLINEFRIENDS,GETSTRANGERS,ADDFRIEND,REMOVEFRIEND
}
