package assignment7;

/**
 * Created by Anthony on 11/29/2016.
 */
public enum ServerAction {
    LOGINSUCCESS,UPDATEPASSWORDRESULT,MESSAGESENT,GROUPMESSAGESENT,
    GROUPS,FRIENDS,OFFLINEFRIENDS,STRANGERS,MAKEGROUP,FRIENDADDED,FRIENDREMOVED, MESSAGEHISTORY, GROUPMESSAGEHISTORY, LEFTGROUP
}
