package assignment7;

/**
 * Created by Anthony on 11/29/2016.
 */
public enum ServerAction {
    LOGINSUCCESS,
    FRIENDS,OFFLINEFRIENDS,STRANGERS,GROUPS,
    MESSAGEHISTORY,GROUPMESSAGEHISTORY,
    FRIENDADDED,FRIENDREMOVED,
    NEWMESSAGE,NEWGROUPMESSAGE
}
