package assignment7;

/**
 * Created by Anthony on 11/29/2016.
 */
public enum ServerAction {
    UPDATEPASSWORDRESULT,MESSAGESENT,GROUPMESSAGESENT,
    GROUPS,FRIENDS,MAKEGROUP,FRIENDADDED,FRIENDREMOVED, MESSAGEHISTORY, GROUPMESSAGEHISTORY, LEFTGROUP
}
